name: Build and Release Executables

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13, macos-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Executable
        run: python -m PyInstaller --distpath o4xp_2_xp12/. --workpath ./OBJ --onefile o4xp_2_xp12.py

      - name: Archive Build Results
        if: startsWith(matrix.os, 'windows')
        run: zip -r o4xp_2_xp12_windows.zip o4xp_2_xp12/*.exe

      - name: Archive Build Results
        if: startsWith(matrix.os, 'ubuntu')
        run: zip -r o4xp_2_xp12_linux.zip o4xp_2_xp12/*.bin

      - name: Archive Build Results
        if: matrix.os == 'macos-13' || matrix.os == 'macos-latest'
        run: zip -r o4xp_2_xp12_mac.zip o4xp_2_xp12/*.bin

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: |
            o4xp_2_xp12_windows.zip
            o4xp_2_xp12_linux.zip
            o4xp_2_xp12_mac.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          prerelease: ${{ contains(github.ref_name, '-') }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/o4xp_2_xp12_windows.zip
          asset_name: o4xp_2_xp12_windows.zip
          asset_content_type: application/zip

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/o4xp_2_xp12_linux.zip
          asset_name: o4xp_2_xp12_linux.zip
          asset_content_type: application/zip

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/o4xp_2_xp12_mac.zip
          asset_name: o4xp_2_xp12_mac.zip
          asset_content_type: application/zip